version: "3.4"

services:
  mongo:
    image: mongo:4.2
    volumes:
      - mongodb-data:/var/lib/mongodb
    ports:
      - 27017:27017

  hapi_app:
    build:
      context: .
    environment:
      DB_CONN_STRING: mongodb://mongo:27017/tickets?retryWrites=true&w=majority

    # in production make sure you are exporting the right ports
    ports:
      - 3000:3000
    depends_on:
      - mongo

volumes:
  mongodb-data:
